steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.test','-t', 'tester', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile', '-t', 'gcr.io/syb-staging-platform/gcb-test', '.']
images: ['gcr.io/syb-staging-platform/gcb-test']


