FROM ubuntu:18.04

COPY web.py /usr/local/bin/
ENV DEBIAN_FRONTEND=noninteractive 
RUN apt-get update && \
    apt-get install -y python-pip pylint

RUN pip install flask

RUN pylint /usr/local/bin/web.py 
